apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: jagannathrk/bookmyevent-auth-dockerfile
          env:
            - name: BME_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: bme-jwt-secret
                  key: BME_JWT_KEY
