apiVersion: skaffold/v2beta4
kind: Config
deploy:
  kubectl:
    manifests:
      - ../k8s/*
build:
  local:
    push: false
  artifacts:
    - image: jagannathrk/bookmyevent-auth-dockerfile
      context: ../app/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: dockerjrk1718/bme-client-df
    #   context: ../app/client
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: '**/*.js'
    #         dest: .
